### ISSUE TITLE
[Bug]: view shakiness

### ISSUE THREAD

**Issue by OrionMoonclaw** [Supreeeme/xrizer#66]
### Operating System

Arch Linux

### OpenXR Runtime

WiVRn

### Describe the issue.

The view seems to occasionally shake, especially if the game is not performing well it feels like it overshoots somewhat or causes double vision. On OpenComposite even if the game is running at a low framerate, rotating the head is always smooth and comfortable.

Files ended up quite big, so I put them up here: [debug](http://media.fawx.news/debug.tar.zst) [release](http://media.fawx.news/release.tar.zst) (don't look at my nose in the videos, that shaking around a bit is normal)

### Steps to reproduce

1. Have WiVRn
2. Launch game
3. Regret

### Please confirm you have reproduced this on the latest commit.

- [x] I have reproduced this on the latest commit

**Comment by SpookySkeletons** [comment]
Monado does not appear to suffer this exact issue but something different, stutter just WiVRn in my testing.

Wired monado does seem to undergo some wobble during intense stutters and low framerate. In those moments you can jiggle your head and watch the projection no longer even conform to gravity, canting the entire world in the frozen reprojection as if the pose or the timing of the projection is not properly set and is messing with how its being presented.

On WiVRn whatever this issue is, presents as frequent stutter and splitting vision.

Despite the differing compositor types I think it suggests something off about how projections are being submitted, somewhere.

**Comment by killthealias** [comment]
Chiming in to add that I've been experiencing this too on Half Life Alyx using XRizer and WiVRn.

**Comment by notpeelz** [comment]
It's especially bad in Resonite.
I'm testing with WiVRn at 120hz in the main menu, where the game runs at a stable 90 FPS.

It kinda looks like this when moving my head side to side (faked with an image editor):
![Image](https://github.com/user-attachments/assets/bba54323-46f6-488c-84d3-813755a3326a)

The issue isn't reproducible with OpenComposite (same refresh rate, same FPS).

**Comment by Supreeeme** [comment]
I suspect this is related to the large number of GetProjectionRaw calls, somehow.
Could you get another set of logs and traces? There have been a couple of compositor changes.

**Comment by mitsuami-megane** [comment]
I'm getting this in Into The Radius 2, but only in the menu. The game itself runs fine. 

Which is weird because the menu is pretty simple with seemingly nothing graphically demanding in there.

**Comment by Supreeeme** [comment]
Into The Radius 2 appears to be an OpenXR game, so it's not using xrizer in this case.

**Comment by Baplar** [comment]
I can reproduce it on Resonite as well, with wivrn+xrizer (latest main as of this message). OpenComposite does not have this behavior.
It only happens when the game hits a lower framerate than the target refresh rate. I target 90Hz on my headset, everything is smooth when the game hits 90fps, but I observe pronounced "shakiness" (similar to notpeelz’s illustration) when I can only hit lower fps (50-ish in the test I just made).
The way it feels to me, is like some frames kind of "overshoot" the head movements by quite a lot (possibly proportional to the amount of time needed to "wait" between 2 "real" frames?), then the next frame is put in the correct location leading to a kind of "whiplash" every couple frames when the head moves. I have absolutely no idea if that has any correspondence to a real thing happening, that’s just my layman’s gut feeling interpretation.

I can try to generate logs. Do I just enable RUST_LOG=trace globally, or do you only need a specific module’s traces?

**Comment by Supreeeme** [comment]
trace is fine yes. Getting a tracy log would be helpful too, which you can do by:
1. Building xrizer with `cargo build -Ftracing`
2. Launch tracy - you should see something you can connect to - if there are two then connect to the second one
3. Reproduce the issue
4. Save the trace

**Comment by Baplar** [comment]
Not sure I did everything right, as this is my first time using tracy, but here goes: https://mega.nz/file/NQslERhJ#-tdPrZFXKEQEnEnbypF7SbGYL1st7QUBCAgBkPXmrv4
I tried switching between an environment with higher FPS and one with lower FPS to try and make the effect more visible.

**Comment by Baplar** [comment]
Interestingly, the effect felt worse when I was closer to half my refresh rate (around 45 fps) than when it dropped lower due to tracy doing its thing during this test (around 30 fps)? But I am not certain how much of this is in my head vs reality

**Comment by OrionMoonclaw** [comment]
I was able to test with both a Quest 3 and a Vive Pro, and I can confirm that it only happens on WiVRn all other hardware being the same

https://paste.fawx.news/vive.zip
https://paste.fawx.news/quest3.zip

**Comment by Supreeeme** [comment]
Well, this will certainly be hard to debug since I don't have a quest. The quest trace actually looks better performance wise., so the traces seem useless here.

The only thought I have is it's related to the view caching. I've pushed up two branches: `early_cache` and `no_caching`. Please let me know how performance differs on these branches, if at all.

**Comment by Baplar** [comment]
`early_cache` feels great! The after-image effect I get on the main branch is no longer present. I get an experience close to OpenComposite with regards to visuals.

On the contrary, `no_caching` feels dreadful, the view shakes as soon as I move my head. It seems to happen to an extent as soon as the framerate dips even a single FPS beneath my headset’s refresh rate, and gets worse the lower it gets. At low FPS, it feels like I’m being rattled in an earthquake.

**Comment by ImSapphire** [comment]
> Well, this will certainly be hard to debug since I don't have a quest. The quest trace actually looks better performance wise., so the traces seem useless here.
> 
> The only thought I have is it's related to the view caching. I've pushed up two branches: `early_cache` and `no_caching`. Please let me know how performance differs on these branches, if at all.

I tested `early_cache` and it definitely improves things, especially in Alyx where it used to jitter/shake several times a second. With that commit applied it's much less frequent, maybe only one or two over a few seconds, but it's still present.

**Comment by Baplar** [comment]
> With that commit applied it's much less frequent, maybe only one or two over a few seconds, but it's still present.

I think I have the same experience, but from my tests, I could sometimes observe similar intermittent jitters with OpenComposite as well, under low FPS and with fast headset movements. I believe this might be hitting a point where the remainder of the bug lies on WiVRn’s side, kinda? I need to do more cross-comparison between OC and this new branch.

**Comment by ImSapphire** [comment]
> I think I have the same experience, but from my tests, I could sometimes observe similar intermittent jitters with OpenComposite as well, under low FPS and with fast headset movements. I believe this might be hitting a point where the remainder of the bug lies on WiVRn’s side, kinda? I need to do more cross-comparison between OC and this new branch.

I was mostly comparing to wlx-overlay-s because I haven't used OC in a while, I never get jitters in wlx. At least Alyx is playable (until one of those weird permanent drops to 10fps hits and you need to restart the game)

**Comment by Mhowser** [comment]
Tested the `early_cache` with my Pico 4 in Resonite and there is no more view shaking!!

**Comment by OrionMoonclaw** [comment]
Looks on par with OpenComposite for me on early_cache!

**Comment by Supreeeme** [comment]
Thanks for the feedback. I just pushed another change to `early_cache`. Please test and let me know how performance changes, if at all. I'll clean it up and merge this stuff into main after this round of feedback.

**Comment by ImSapphire** [comment]
> Thanks for the feedback. I just pushed another change to `early_cache`. Please test and let me know how performance changes, if at all. I'll clean it up and merge this stuff into main after this round of feedback.

I'm getting 90fps in Alyx! Feels very smooth, haven't noticed any jitters.
